Exception on / [GET]
Traceback (most recent call last):
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: readQueryList() missing 1 required positional argument: 'data'
Exception on / [GET]
Traceback (most recent call last):
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/esakkiraja/projects/wallaceTimer/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
TypeError: readQueryList() missing 1 required positional argument: 'data'
Read Query function: No data found
Read Query function: No data found
